title: Touba Shah # place name (or website title) here
logo: "https://media-exp1.licdn.com/dms/image/C5603AQG1o6d6vbZxRQ/profile-displayphoto-shrink_200_200/0?e=1585785600&v=beta&t=yJlIblhSaTx8jO6AfypWtFanh7F96_NkBYKOOYBg-Xg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  B.S student in Environemental Science at the Univerity of Maryland Baltimore County, expected gradution in May 2020. Four year experience in corrosion reserach of various alloys in mooten salt for application in renewable energy. 
  Experienced in ArcGIS, R, Python, Matlab, and excel. 
  
  ...
  Currently reseraching in rain rate data from HydroNEXRAD and DPR for analysis in Baltimore County region. 
  ...
  Linkedin Page:
  <a href="www.linkedin.com/in/touba-shah-436025125">View My LinkedIn Profile</a> 
  ...
  Github Page: 
  <a href="https://tshah2.github.io/">View My GitHub Profile</a> 
  
# Ignore these two parts
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
